const FLATS_GET_REQ = "FLATS_GET_REQ";
const FLATS_GET_SUCCESS = "FLATS_GET_SUCCESS";
const FLATS_GET_FAILURE = "FLATS_GET_FAILURE";

const ADD_FLAT_REQ = "ADD_FLAT_REQ";
const ADD_FLAT_SUCCESS = "ADD_FLAT_SUCCESS";
const ADD_FLAT_FAILURE = "ADD_FLAT_FAILURE";

export {
  FLATS_GET_REQ,
  FLATS_GET_SUCCESS,
  FLATS_GET_FAILURE,
  ADD_FLAT_SUCCESS,
  ADD_FLAT_FAILURE,
  ADD_FLAT_REQ,
};
